//
//  MuzSzafaSharedTests.swift
//  MuzSzafaSharedTests
//
//  Created by Alagris on 22/03/2018.
//  Copyright © 2018 alagris. All rights reserved.
//

import XCTest
@testable import MuzSzafaShared

class PaymentCreationTests: XCTestCase {
	
	func test(){
		CoreContext.shared.purge()
		UserDefaults.standard.singleTermLengthDays = 0
		UserDefaults.standard.singleTermLengthHours = 0
		UserDefaults.standard.singleTermLengthYears = 0
		UserDefaults.standard.singleTermLengthMonths = 1
		UserDefaults.standard.singleTermLengthMinutes = 0
		
		
		let c = Client.ent.newAutogenerated() as! Client
		let i = Instrument.ent.newAutogenerated() as! Instrument
		
		let deal = Deal.ensureExists(id: "id", client: c, instrument: NSSet(array: [i]))
		let dateReader = CoreDataDateSerializer()
		let zero = dateReader.deserialize("10-6-2018")!
		let one = zero.increaseBySingleTermLength()!
		let two = one.increaseBySingleTermLength()!
		let three = two.increaseBySingleTermLength()!
		deal.from = zero
		let payment1 = Payment.createNew(deal)!
		let payment2 = Payment.createNew(deal)!
		let payment3 = Payment.createNew(deal)!
		XCTAssertEqual(payment1.term_begin, zero)
		XCTAssertEqual(payment1.term_end, one)
		XCTAssertEqual(payment2.term_begin, one)
		XCTAssertEqual(payment2.term_end, two)
		XCTAssertEqual(payment3.term_begin, two)
		XCTAssertEqual(payment3.term_end, three)
	}
    
}
